AllCops:
  NewCops: enable
  Exclude:
    - 'Pods/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Enabled: false
