test:
	swift test --enable-code-coverage
generate-project:
	# optionally makes an xcodeproj (instead of opening the package directly)
	swift package generate-xcodeproj --enable-code-coverage
open:
	open Package.swift
